# Generated by Django 5.2.4 on 2025-09-24 20:46

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, storage=contact.models.get_supabase_storage, upload_to='contacts/'),
        ),
    ]
